version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - npm i
  build:
    commands:
      - npm run build
      
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
  
cache:
  paths:
    - 'node_modules/**/**'
